# This is a sample build configuration for Other.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: ruby:2.5

definitions:
  caches:
    bundler: vendor/bundle
  steps:
    - step: &build
        name: Build project
        script:
          - gem install jekyll bundler
          - jekyll build
        artifacts:
          - _site/**

pipelines:
  branches:
    develop:
    - step: *build
    - step:
        name: Deploy project (test)
        deployment: test
        script:
          - rm CNAME
          - git remote set-url origin https://${GitHub_User}:${GitHub_Token}@github.com/navacamicie/beta.git
          - git add .
          - git commit -a -m "auto build ${BITBUCKET_BUILD_NUMBER}"
          - git push -f
          - git fetch origin
          - git checkout -b master
          - git merge develop
          - git push -f

    master:
    - step: *build
    - step:
        name: Deploy project (production)
        deployment: production
        script:
          - git remote set-url origin https://${GitHub_User}:${GitHub_Token}@github.com/navacamicie/navacamicie.github.io.git
          - git add .
          - git commit -a -m "auto build ${BITBUCKET_BUILD_NUMBER}"
          - git push -f
          - git fetch origin
          - git checkout -b master
          - git merge develop
          - git push -f
